services:
  storage:
    image: minio/minio
    command: minio server /data
    volumes:
      - storaga_data:/data
    restart: always
    environment:
      MINIO_ACCESS_KEY: fakeaccesskey
      MINIO_SECRET_KEY: fakeaccesskey
    ports:
      - 9000:9000

  frontend:
    build: .
    command: python3 server.py
    volumes: 
      - type: bind
        source: .
        target: /app
    environment:
      PYTHONDOWNTWRITEBYTECODE: 1
      S3_ENDPOINT: http://storage:9000
      S3_USE_PATH_STYLE: 1
      S3_ACCESS_KEY: fakeaccesskey 
      S3_SECRET_ACCESS_KEY: fakeaccesskey
    ports:
      - "8080:80"
volumes:
  db_data:
  storaga_data:
